### ISSUE TITLE
Propuesta de proyecto

### ISSUE THREAD

**Issue by SoledadQuiroz** [SoledadQuiroz/FullStack-ProyectoIntegrador#6]
Completar la  [Planilla Propuestas de Proyecto](https://docs.google.com/document/d/1KS5O2OfU_QO-HMQ76KRjsvpwRKMLy9mBi20_KJKeks0/edit?usp=sharing) (hacer copia por grupo) con 2 (dos) ideas de potenciales proyectos de desarrollo de software.

**Comment by GerLR** [comment]
Planilla completa y subida a la plataforma
